import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shahin Alam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white/90 bg-primary">
      <div className="fixed flex h-screen items-center">
        <NavBar></NavBar>
        </div>
        {children}
        </body>
    </html>
  );
}
